server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # Eureka server should not register with itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # Use the container name for Docker networking
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    # Use hostname instead of IP for Docker
    hostname: eureka-server
    prefer-ip-address: false
  server:
    # Disable self-preservation for development
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

# Enable management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always

# Optional: Add logging for debugging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO