server:
  port: 8083

spring:
  application:
    name: booking-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: booking-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, mappings
  endpoint:
    health:
      show-details: always
